/**
 * Shared key/value store with TTL — server-side only.
 *
 * WHY THIS EXISTS
 * ---------------
 * Auth codes and rate-limit counters were held in module-level `new Map()`s.
 * That works on a single long-lived server and fails on serverless:
 *
 *   - Vercel runs many isolated instances. A verification code generated by
 *     instance A is invisible to instance B, so "Invalid or expired code"
 *     appeared at random for legitimate users. This was a correctness bug in
 *     signup and password reset, not merely a security gap.
 *   - Rate limits were per-instance, so the effective limit was
 *     (configured limit x number of warm instances) — i.e. largely unenforced.
 *
 * Backend selection is automatic:
 *   1. Firestore via firebase-admin, when a service account is configured.
 *      Chosen because the project already depends on firebase-admin — no new
 *      service, account, or credential is required.
 *   2. In-memory Map, for local development and as a graceful degradation.
 *      Correct on a single process; the same split-brain caveat applies if it
 *      is ever hit in production, so we warn loudly.
 */

interface Entry {
  value: unknown;
  expiresAt: number;
}

const memory = new Map<string, Entry>();
let warnedMemoryFallback = false;

/** Periodically drop expired in-memory entries so the Map cannot grow forever. */
function sweepMemory() {
  const now = Date.now();
  for (const [k, v] of memory.entries()) {
    if (v.expiresAt < now) memory.delete(k);
  }
}

/** Firestore collection used for ephemeral server state. */
const COLLECTION = "_ephemeral";

async function getDb() {
  try {
    const { getAdminDb } = await import("@/lib/firebase-admin");
    return await getAdminDb();
  } catch {
    return null;
  }
}

function warnMemory(op: string) {
  if (warnedMemoryFallback) return;
  warnedMemoryFallback = true;
  console.warn(
    `[shared-store] Using in-memory fallback for "${op}". On serverless this ` +
      "is per-instance: auth codes may not verify and rate limits will not be " +
      "enforced across instances. Set FIREBASE_SERVICE_ACCOUNT to enable the " +
      "shared Firestore backend."
  );
}

/** Store a value under `key`, expiring after `ttlMs`. */
export async function put(key: string, value: unknown, ttlMs: number): Promise<void> {
  const expiresAt = Date.now() + ttlMs;
  const db = await getDb();

  if (db) {
    try {
      await db.collection(COLLECTION).doc(encodeKey(key)).set({ value, expiresAt });
      return;
    } catch (err) {
      console.error("[shared-store] Firestore put failed, falling back:", err);
    }
  }

  warnMemory("put");
  sweepMemory();
  memory.set(key, { value, expiresAt });
}

/** Read a value, or null when missing/expired. Expired entries are removed. */
export async function get<T = unknown>(key: string): Promise<T | null> {
  const db = await getDb();

  if (db) {
    try {
      const snap = await db.collection(COLLECTION).doc(encodeKey(key)).get();
      if (!snap.exists) return null;
      const data = snap.data() as Entry | undefined;
      if (!data) return null;
      if (data.expiresAt < Date.now()) {
        await db.collection(COLLECTION).doc(encodeKey(key)).delete().catch(() => {});
        return null;
      }
      return data.value as T;
    } catch (err) {
      console.error("[shared-store] Firestore get failed, falling back:", err);
    }
  }

  warnMemory("get");
  const entry = memory.get(key);
  if (!entry) return null;
  if (entry.expiresAt < Date.now()) {
    memory.delete(key);
    return null;
  }
  return entry.value as T;
}

/** Remove a key. */
export async function del(key: string): Promise<void> {
  const db = await getDb();
  if (db) {
    try {
      await db.collection(COLLECTION).doc(encodeKey(key)).delete();
      return;
    } catch (err) {
      console.error("[shared-store] Firestore delete failed, falling back:", err);
    }
  }
  memory.delete(key);
}

/**
 * Atomically increment a counter within a fixed window.
 *
 * Returns the count after incrementing and when the window resets. Uses a
 * Firestore transaction so concurrent requests across instances cannot each
 * read the same pre-increment value and collectively exceed the limit.
 */
export async function incrementInWindow(
  key: string,
  windowMs: number
): Promise<{ count: number; resetAt: number }> {
  const now = Date.now();
  const db = await getDb();

  if (db) {
    try {
      const ref = db.collection(COLLECTION).doc(encodeKey(key));
      return await db.runTransaction(async (tx: any) => {
        const snap = await tx.get(ref);
        const data = snap.exists ? (snap.data() as { count?: number; expiresAt?: number }) : null;

        if (!data || !data.expiresAt || data.expiresAt < now) {
          const resetAt = now + windowMs;
          tx.set(ref, { count: 1, expiresAt: resetAt });
          return { count: 1, resetAt };
        }

        const count = (data.count || 0) + 1;
        tx.set(ref, { count, expiresAt: data.expiresAt }, { merge: true });
        return { count, resetAt: data.expiresAt };
      });
    } catch (err) {
      console.error("[shared-store] Firestore increment failed, falling back:", err);
    }
  }

  warnMemory("increment");
  sweepMemory();
  const entry = memory.get(key) as { value: number; expiresAt: number } | undefined;
  if (!entry || entry.expiresAt < now) {
    const resetAt = now + windowMs;
    memory.set(key, { value: 1, expiresAt: resetAt });
    return { count: 1, resetAt };
  }
  const count = (entry.value as number) + 1;
  memory.set(key, { value: count, expiresAt: entry.expiresAt });
  return { count, resetAt: entry.expiresAt };
}

/** Firestore document ids cannot contain "/" and are length-limited. */
function encodeKey(key: string): string {
  return encodeURIComponent(key).replace(/%/g, "_").slice(0, 400);
}

/** True when the shared (cross-instance) backend is available. */
export async function isShared(): Promise<boolean> {
  return Boolean(await getDb());
}
